sudo: false
language: go
go:
  - 1.11.5

before_install:
  - make get-build-deps
script:
  - make build

after_success:
 - curl --request POST "https://goreportcard.com/checks" --data "repo=github.com/reportportal/commons-go"
 - bash <(curl -s https://codecov.io/bash)
